export type Kode = "id" | "en";

const ID = {
  nav_favorit: "Favorit",
  nav_tambah: "+ Tambah",
  nav_tema_terang: "Ganti ke mode terang",
  nav_tema_gelap: "Ganti ke mode gelap",
  nav_bahasa: "Ganti bahasa",

  hero_judul: "Hai, mau makan apa hari ini?",
  hero_isi:
    "Cari tempat makan di sekitar kampus ITS, bandingkan harga dan rating, lalu tulis penilaianmu sendiri.",
  cari_placeholder: "Cari bakso, soto, atau nama menu...",
  cari_label: "Cari tempat makan",
  chip_rating: "Rating 4.5+",
  chip_hemat: "Hemat di bawah 15k",
  chip_reset: "Reset",

  kategori_semua: "Semua",
  urut_label: "Urutkan",
  urut_rating: "Rating",
  urut_murah: "Termurah",
  urut_mahal: "Termahal",
  urut_populer: "Terpopuler",
  urut_nama: "A-Z",

  badge_best: "Best Seller",
  badge_rekomendasi: "Rekomendasi",
  promosi: "Promosi",
  banner_sebelum: "Banner sebelumnya",
  banner_sesudah: "Banner berikutnya",
  banner_lihat: (n: number) => `Lihat banner ${n}`,
  banner1_judul: "Paling dicari minggu ini",
  banner1_isi: "Gepuk Geprek CCWS IKOMA, 51 review dari mahasiswa",
  banner2_judul: "Ngemil hemat mulai Rp2.000",
  banner2_isi: "Pisang Goreng Kantin Pusat, pas buat nunggu kelas",
  banner3_judul: "Rating tertinggi 4.7",
  banner3_isi: "Pecel Perpustakaan Pusat, favorit buat sarapan",
  banner4_judul: "Buka paling pagi 07.00",
  banner4_isi: "Sego Jamur Kantin Pusat, murah dan cepat",

  daftar_semua: "Semua tempat makan",
  menampilkan: (a: number, b: number) => `Menampilkan ${a} dari ${b} tempat`,
  kosong_judul: "Belum ada yang cocok",
  kosong_isi: "Coba ganti kata kunci atau matikan saringannya.",
  kosong_tombol: "Reset saringan",
  kartu_review: (n: number) => `${n} review`,

  detail_kembali: "Kembali",
  detail_dari_review: (n: number) => `dari ${n} review`,
  detail_simpan: "Simpan favorit",
  detail_tersimpan: "Tersimpan",
  detail_kategori: "Kategori",
  detail_jam: "Jam buka",
  detail_harga: "Kisaran harga",
  detail_menu: "Daftar Menu",
  detail_menu_kosong: "Menu belum didata. Kamu bisa jadi yang pertama menambahkannya.",
  detail_lokasi: "Lokasi",
  detail_peta_link: "Buka di Google Maps",
  detail_peta_judul: (n: string) => `Peta lokasi ${n}`,
  detail_hilang: "Tempat tidak ditemukan.",
  detail_ke_beranda: "Kembali ke beranda",

  menu_tambah_tombol: "+ Tambah menu di tempat ini",
  menu_tambah_judul: "Tambah menu",
  menu_nama: "Nama menu",
  menu_harga: "Harga",
  menu_badge: "Badge menu",
  menu_tanpa_badge: "Tanpa badge",
  menu_simpan: "Simpan menu",
  menu_batal: "Batal",
  menu_catatan:
    "Siapa pun yang tahu menunya boleh menambahkan, bukan hanya pemilik tempat.",
  menu_err_nama: "Nama menu wajib diisi.",
  menu_err_harga: "Harga harus berupa angka.",
  menu_err_negatif: "Harga tidak boleh negatif.",
  menu_err_kembar: "Menu dengan nama itu sudah ada di daftar.",
  menu_err_penuh: "Penyimpanan browser penuh.",

  review_judul: "Tulis Review",
  review_nama: "Nama",
  review_nama_placeholder: "Nama kamu",
  review_rating: "Rating",
  review_komentar: "Komentar",
  review_komentar_placeholder: "Gimana rasanya, porsinya, antrinya?",
  review_foto: "Foto makanan (opsional)",
  review_kirim: "Kirim Review",
  review_daftar: (n: number) => `Review (${n})`,
  review_kosong: "Belum ada review. Jadi yang pertama!",
  review_err_kosong: "Nama dan komentar wajib diisi.",
  review_err_rating: "Rating harus antara 1 sampai 5.",
  review_err_kembar: "Kamu sudah pernah menulis review untuk tempat ini.",
  review_foto_dari: (n: string) => `Foto makanan dari ${n}`,

  rating5: "5 - Enak banget",
  rating4: "4 - Enak",
  rating3: "3 - Biasa",
  rating2: "2 - Kurang",
  rating1: "1 - Tidak enak",

  fav_judul: "Tempat Favorit",
  fav_isi: "Tempat makan yang kamu simpan tersimpan di browser ini.",
  fav_kosong_judul: "Belum ada favorit",
  fav_kosong_isi: "Buka salah satu tempat lalu tekan Simpan favorit.",
  fav_kosong_tombol: "Cari tempat makan",
  fav_jumlah: (n: number) => `${n} tempat tersimpan`,
  fav_hapus: "Hapus dari favorit",

  baru_judul: "Tambah Tempat Makan",
  baru_isi: "Lengkapi data tempat makan di sekitar ITS yang belum ada di daftar.",
  baru_nama: "Nama tempat",
  baru_kategori: "Kategori",
  baru_alamat: "Alamat",
  baru_jam: "Jam buka",
  baru_min: "Harga minimum",
  baru_max: "Harga maksimum",
  baru_foto: "Foto tempat (opsional)",
  baru_foto_hapus: "Hapus foto",
  baru_menu_judul: "Daftar menu (opsional)",
  baru_menu_isi:
    "Boleh dikosongkan. Pengguna lain bisa menambahkan menu setelah tempat ini terbit.",
  baru_menu_tambah: "+ Tambah ke daftar menu",
  baru_menu_hapus: (n: string) => `Hapus menu ${n}`,
  baru_menu_err_kembar: "Menu dengan nama itu sudah ditambahkan.",
  baru_menu_err_harga: "Harga menu harus berupa angka dan tidak boleh negatif.",
  baru_simpan: "Simpan Tempat",
  baru_err_wajib: "Nama, alamat, dan jam buka wajib diisi.",
  baru_err_angka: "Harga minimum dan maksimum harus berupa angka.",
  baru_err_negatif: "Harga tidak boleh negatif.",
  baru_err_urutan: "Harga minimum tidak boleh lebih besar dari harga maksimum.",
  baru_err_kembar: "Tempat dengan nama itu sudah terdaftar.",
  baru_err_penuh: "Penyimpanan browser penuh. Pakai foto yang lebih kecil.",

  foto_bukan_gambar: "Berkas yang dipilih bukan gambar.",
  foto_terlalu_besar: "Ukuran foto maksimal 8 MB.",
  foto_gagal: "Foto gagal dibaca, coba gambar lain.",
  foto_pratinjau_tempat: "Pratinjau foto tempat",
  foto_pratinjau_review: "Pratinjau foto review",
};

export type Pesan = typeof ID;

const EN: Pesan = {
  nav_favorit: "Saved",
  nav_tambah: "+ Add",
  nav_tema_terang: "Switch to light mode",
  nav_tema_gelap: "Switch to dark mode",
  nav_bahasa: "Change language",

  hero_judul: "Hi, what do you want to eat?",
  hero_isi:
    "Find places to eat around ITS, compare prices and ratings, and leave your own review.",
  cari_placeholder: "Search for bakso, soto, or a dish...",
  cari_label: "Search places",
  chip_rating: "Rating 4.5+",
  chip_hemat: "Under Rp15,000",
  chip_reset: "Reset",

  kategori_semua: "All",
  urut_label: "Sort by",
  urut_rating: "Rating",
  urut_murah: "Cheapest",
  urut_mahal: "Priciest",
  urut_populer: "Most reviewed",
  urut_nama: "A-Z",

  badge_best: "Best Seller",
  badge_rekomendasi: "Recommended",
  promosi: "Promo",
  banner_sebelum: "Previous banner",
  banner_sesudah: "Next banner",
  banner_lihat: (n: number) => `Go to banner ${n}`,
  banner1_judul: "Most searched this week",
  banner1_isi: "Gepuk Geprek CCWS IKOMA, with 51 student reviews",
  banner2_judul: "Snacks from Rp2,000",
  banner2_isi: "Pisang Goreng Kantin Pusat, perfect between classes",
  banner3_judul: "Top rated, 4.7 stars",
  banner3_isi: "Pecel Perpustakaan Pusat, a breakfast favorite",
  banner4_judul: "Opens earliest, 7 AM",
  banner4_isi: "Sego Jamur Kantin Pusat, cheap and quick",

  daftar_semua: "All places",
  menampilkan: (a: number, b: number) => `Showing ${a} of ${b} places`,
  kosong_judul: "No results",
  kosong_isi: "Try a different keyword, or clear the filters.",
  kosong_tombol: "Clear filters",
  kartu_review: (n: number) => (n === 1 ? "1 review" : `${n} reviews`),

  detail_kembali: "Back",
  detail_dari_review: (n: number) =>
    n === 1 ? "based on 1 review" : `based on ${n} reviews`,
  detail_simpan: "Save",
  detail_tersimpan: "Saved",
  detail_kategori: "Category",
  detail_jam: "Open",
  detail_harga: "Price range",
  detail_menu: "Menu",
  detail_menu_kosong: "No menu listed yet. Be the first to add one.",
  detail_lokasi: "Location",
  detail_peta_link: "Open in Google Maps",
  detail_peta_judul: (n: string) => `Map of ${n}`,
  detail_hilang: "We could not find that place.",
  detail_ke_beranda: "Back to home",

  menu_tambah_tombol: "+ Add a menu item",
  menu_tambah_judul: "Add a menu item",
  menu_nama: "Dish name",
  menu_harga: "Price",
  menu_badge: "Badge",
  menu_tanpa_badge: "No badge",
  menu_simpan: "Save item",
  menu_batal: "Cancel",
  menu_catatan:
    "Anyone who knows the menu can add items here, not just the owner.",
  menu_err_nama: "Please enter a dish name.",
  menu_err_harga: "Price has to be a number.",
  menu_err_negatif: "Price cannot be negative.",
  menu_err_kembar: "That dish is already on the list.",
  menu_err_penuh: "Browser storage is full.",

  review_judul: "Write a Review",
  review_nama: "Name",
  review_nama_placeholder: "Your name",
  review_rating: "Rating",
  review_komentar: "Comment",
  review_komentar_placeholder: "How was the food, the portion, the wait?",
  review_foto: "Photo of your food (optional)",
  review_kirim: "Post Review",
  review_daftar: (n: number) => (n === 1 ? "1 Review" : `${n} Reviews`),
  review_kosong: "No reviews yet. Be the first!",
  review_err_kosong: "Please fill in your name and comment.",
  review_err_rating: "Rating has to be between 1 and 5.",
  review_err_kembar: "You have already reviewed this place.",
  review_foto_dari: (n: string) => `Food photo from ${n}`,

  rating5: "5 - Delicious",
  rating4: "4 - Good",
  rating3: "3 - Just okay",
  rating2: "2 - Not great",
  rating1: "1 - Bad",

  fav_judul: "Saved Places",
  fav_isi: "The places you save are kept in this browser.",
  fav_kosong_judul: "Nothing saved yet",
  fav_kosong_isi: "Open a place and tap Save to keep it here.",
  fav_kosong_tombol: "Browse places",
  fav_jumlah: (n: number) => (n === 1 ? "1 place saved" : `${n} places saved`),
  fav_hapus: "Remove",

  baru_judul: "Add a Place",
  baru_isi: "Add a place around ITS that is not on the list yet.",
  baru_nama: "Place name",
  baru_kategori: "Category",
  baru_alamat: "Address",
  baru_jam: "Opening hours",
  baru_min: "Lowest price",
  baru_max: "Highest price",
  baru_foto: "Photo of the place (optional)",
  baru_foto_hapus: "Remove photo",
  baru_menu_judul: "Menu (optional)",
  baru_menu_isi:
    "You can leave this empty. Other people can add dishes once the place is live.",
  baru_menu_tambah: "+ Add to menu",
  baru_menu_hapus: (n: string) => `Remove ${n}`,
  baru_menu_err_kembar: "You have already added that dish.",
  baru_menu_err_harga: "Price has to be a number and cannot be negative.",
  baru_simpan: "Save Place",
  baru_err_wajib: "Please fill in the name, address, and opening hours.",
  baru_err_angka: "Lowest and highest price have to be numbers.",
  baru_err_negatif: "Price cannot be negative.",
  baru_err_urutan: "The lowest price cannot be higher than the highest.",
  baru_err_kembar: "A place with that name is already on the list.",
  baru_err_penuh: "Browser storage is full. Try a smaller photo.",

  foto_bukan_gambar: "That file is not an image.",
  foto_terlalu_besar: "The photo has to be under 8 MB.",
  foto_gagal: "We could not read that photo. Try another one.",
  foto_pratinjau_tempat: "Preview of the place photo",
  foto_pratinjau_review: "Preview of the review photo",
};

export const KAMUS: Record<Kode, Pesan> = { id: ID, en: EN };
